### ISSUE TITLE
Image paths are not working on build

### ISSUE THREAD

**Issue by skkr** [windingtree/wt-ui#80]
Until now webpack config was set to put the images in `/img`

Since now we have assets with the same names (which are in different folders) this method wont work. Wee need to keep the different paths.

This has been updated already, but doesn't looks well because node_modules is included on the the final.

`img/node_modules/@windingtree/wt-ui-assets/logo-variants/full-logo/svg/wt-grad.svg`

Apart from this issue, the images are not loading after running the storybook-build command.

**Comment by PabloAlice** [comment]
> Apart from this issue, the images are not loading after running the storybook-build command.

Currently, we have 2 builds, one for storybook that would let us deploy our storybook docs and another for exporting css files, which is used to upload css to npm repository.
- the second build has no images because there is no css file  importing images.
- the storybook build (docs folder) has images but with the long path that you were talking about.

**Comment by PabloAlice** [comment]
Also, how do you think an image filename should be?
we can use a hash to be sure it won't have the same name, but you should be aware that the filename won't be "nice".
ie: ```123y1f23hyf1d23ghf12d413f417256efd263rdc1qy6r3dc2673rdc1762rf12erc12r6dc273rdc13d.filename.ext```

let me know what do you think

**Comment by skkr** [comment]
If we can keep the image names and paths I'd prefer that option, but I guess is fine, let's choose the simplest solution.

**Comment by PabloAlice** [comment]
I don't understand... what is this issue for?

**Comment by skkr** [comment]
@PabloAlice , thanks for resolving this! Closing... :)
